### ISSUE TITLE
Bug em pubLib05hcode-distrib

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/pg_pubLib-v1#3]
Em `CREATE or replace FUNCTION hcode_distribution_reduce_pre_raw()` de [pubLib05hcode-distrib.sql](https://github.com/AddressForAll/pg_pubLib-v1/blob/main/src/pubLib05hcode-distrib.sql) 
```
 ERROR:  return type mismatch in function declared to return record
DETAIL:  Final statement returns bigint instead of integer at column 4.
CONTEXT:  SQL function "hcode_distribution_reduce_pre_raw"
```

**Comment by 0e1** [comment]
Resolvido pela alteração: https://github.com/AddressForAll/pg_pubLib-v1/commit/8f92f7cc2426258b115416301efc704948055213
