### ISSUE TITLE
Bug em sqls pg_pubLib-v1

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/pg_pubLib-v1#6]
pubLib01py-string.sql

ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/plpython3u.control": No such file or directory
ERROR:  language "plpython3u" does not exist
HINT:  Use CREATE EXTENSION to load the language into the database.
ERROR:  language "plpython3u" does not exist
HINT:  Use CREATE EXTENSION to load the language into the database.
ERROR:  language "plpython3u" does not exist
HINT:  Use CREATE EXTENSION to load the language into the database.
ERROR:  language "plpython3u" does not exist
HINT:  Use CREATE EXTENSION to load the language into the database.
ERROR:  function yaml_to_jsonb(text) does not exist
LINE 2:   SELECT yaml_to_jsonb( pg_read_file(file) )

pubLib03-json.sql

ERROR:  a column definition list is required for functions returning "record"
LINE 9:        FROM array_fillto_duo($1,$2) t(a,b)
                    ^
CREATE FUNCTION
CREATE FUNCTION
pubLib04-aggregate.sql
CREATE FUNCTION
NOTICE:  aggregate array_agg_cat(anyarray) does not exist, skipping
DROP AGGREGATE
CREATE AGGREGATE
NOTICE:  aggregate array_agg_cat_distinct(anyarray) does not exist, skipping
DROP AGGREGATE
CREATE AGGREGATE
NOTICE:  aggregate jsonb_summable_aggmerge(jsonb) does not exist, skipping
DROP AGGREGATE
CREATE AGGREGATE
pubLib05hcode-distrib.sql

**Comment by 0e1** [comment]
Erros já contornados. Fechando issue.
